# --- 1. SUBSCRIPTION PRICING ---
pricing:
  stripe_price_ids:
    explore:
      monthly: price_1RE3tSQTBcqmUQgtoNyD0LgB
      yearly: price_1REVjKQTBcqmUQgt4Z47P00s
    professional:
      monthly: price_1REVwmQTBcqmUQgtiBBLNZaD
      yearly: price_1REVzZQTBcqmUQgtpyBz8Gky
  
  # Price amounts in euros
  price_values:
    explore:
      monthly: 29.00
      yearly_per_month: 26.00
    professional:
      monthly: 44.00
      yearly_per_month: 39.00