color_scheme:
  colors:
  - {color: '#9E9E9E', name: Accent 1}
  - {color: '#616161', name: Accent 2}
  - {color: '#D7D7D7', name: Background}
  - {color: '#333333', name: Header Background}
  - {color: 'rgb(51, 51, 51)', name: Sidebar Background}
  - {color: 'rgb(25, 28, 26)', name: Main_Black}
  - {color: 'rgb(40, 40, 40)', name: Grid_Black}
  - {color: 'rgb(253, 101, 45)', name: Orange}
  - {color: 'rgb(255, 255, 255)', name: Text_White}
  - {color: 'rgb(235, 235, 235)', name: Text_DecentWhite}
  - {color: 'rgb(200, 200, 200)', name: Text_Grey}
  - {color: 'rgb(175, 175, 175)', name: Text_DarkGrey}
  - {color: 'rgb(40, 40, 40)', name: Text_LightBlack}
  - {color: 'rgba(253, 101, 45, 0.2)', name: Accent 3}
  preset_groups:
  - name: Accent
    options:
    - colors:
      - {color: '#2196F3', name: Accent 1}
      - {color: '#1976D2', name: Accent 2}
      name: Blue
    - colors:
      - {color: '#FF9800', name: Accent 1}
      - {color: '#F57C00', name: Accent 2}
      name: Orange
    - colors:
      - {color: '#F44336', name: Accent 1}
      - {color: '#D32F2F', name: Accent 2}
      name: Red
    - colors:
      - {color: '#E91E63', name: Accent 1}
      - {color: '#C2185B', name: Accent 2}
      name: Pink
    - colors:
      - {color: '#9C27B0', name: Accent 1}
      - {color: '#7B1FA2', name: Accent 2}
      name: Purple
    - colors:
      - {color: '#673AB7', name: Accent 1}
      - {color: '#512DA8', name: Accent 2}
      name: Deep Purple
    - colors:
      - {color: '#3F51B5', name: Accent 1}
      - {color: '#303F9F', name: Accent 2}
      name: Indigo
    - colors:
      - {color: '#03A9F4', name: Accent 1}
      - {color: '#0288D1', name: Accent 2}
      name: Light Blue
    - colors:
      - {color: '#00BCD4', name: Accent 1}
      - {color: '#0097A7', name: Accent 2}
      name: Cyan
    - colors:
      - {color: '#009688', name: Accent 1}
      - {color: '#00796B', name: Accent 2}
      name: Teal
    - colors:
      - {color: '#4CAF50', name: Accent 1}
      - {color: '#388E3C', name: Accent 2}
      name: Green
    - colors:
      - {color: '#8BC34A', name: Accent 1}
      - {color: '#689F38', name: Accent 2}
      name: Light Green
    - colors:
      - {color: '#CDDC39', name: Accent 1}
      - {color: '#AFB42B', name: Accent 2}
      name: Lime
    - colors:
      - {color: '#FF5722', name: Accent 1}
      - {color: '#E64A19', name: Accent 2}
      name: Deep orange
    - colors:
      - {color: '#795548', name: Accent 1}
      - {color: '#5D4037', name: Accent 2}
      name: Brown
    - colors:
      - {color: '#9E9E9E', name: Accent 1}
      - {color: '#616161', name: Accent 2}
      name: Grey
roles:
- components: [Label, RichText]
  display_in_toolbox: false
  name: header-1
- components: [ColumnPanel]
  display_in_toolbox: false
  name: card
  title: Card
- components: [Label, Link, RichText]
  name: description
- components: [Label, Link]
  name: artist_name
- components: [GridPanel, ColumnPanel, Link, Image, XYPanel, LinearPanel, FlowPanel]
  name: grid
- components: [Label, Button]
  name: feature
- components: [Label]
  name: value
- components: [Button]
  name: eval_button
- components: [Label]
  name: sub_title
- components: [RepeatingPanel, Link, Label]
  name: table_content
- components: [TextBox]
  name: text_box
- components: [Button]
  name: call_to_action_button
- components: [ColumnPanel]
  name: landingpage_noartists_background
- components: [ColumnPanel]
  name: landingpage_artist_background
- components: [ColumnPanel]
  name: landingpage_artist2_background
- components: [ColumnPanel]
  name: input_margin
- components: [RepeatingPanel, Link, Label]
  name: table_content_small
- components: [DataGrid]
  name: table_header
- components: [Label, Link]
  name: investigate_value
- components: [Label, Link]
  name: investigate_feature
- components: [TextBox, DropDown, TextArea, DatePicker]
  name: text_box_small
- components: [Label, Link, RichText]
  name: artist_name_shadow
- components: [Label]
  name: note
- components: [XYPanel]
  name: bottom_line
- components: [Link]
  name: nav_main
- components: [Link]
  name: nav_sub
- components: [Link]
  name: table_content_small_orange_underlined
- components: [Link]
  name: little_note
- components: [RichText, Label]
  name: description-bio
- components: [RepeatingPanel]
  name: table_content_popup
- components: [DropDown]
  name: related-artist-search-dropdown-header
- components: [Label]
  name: table_content_talent_dev
- components: [Label]
  name: talent-dev-custom-class
- components: [Label]
  name: center-table-element
- components: [RowTemplate]
  name: rows_dropdown
- components: [RowTemplate]
  name: rows_discover_page
- components: [Button, Link]
  name: section_buttons
- components: [Label]
  name: sort-label
- components: [Label]
  name: Discover_artist_name
- components: [FlowPanel]
  display_in_toolbox: false
  name: Discover_xypanel
- components: [XYPanel]
  name: col-artist
- components: [Image]
  name: col-artist-image
- components: [Label, Link]
  display_in_toolbox: false
  name: table_content_talent_dev-1
- components: [Link, Label]
  name: table_content_talent_dev-2
- components: [Button]
  name: feature-talent-dev
- components: [Label, Link]
  name: transparent-headers
- components: [Link, Label]
  name: left-alignment-header
- components: [Link]
  name: underline-link
- components: [Image]
  name: artist-image-tables
- components: [Link]
  name: artist_name_shadow_arrows_left
- components: [Link]
  name: 'artist_name_shadow_arrows_right '
- components: [Link]
  name: 'artist_name_shadow_arrows_left_home '
- components: [Link]
  name: 'artist_name_shadow_arrows_right_home '
- components: [RowTemplate]
  name: rows_discover_page_no_image_table
- components: [ColumnPanel]
  name: grid-main
- components: [Link]
  name: description-bio-link
- components: [FlowPanel]
  name: section-background
- components: [DropDown, DatePicker, TextBox]
  name: target-dropdown
- components: [TextArea]
  name: target-textarea
- components: [RepeatingPanel]
  name: sidebar-notes
- components: [Label]
  name: timestamp-note-format
- components: [Label]
  name: content-note-format
- components: [Button]
  name: save-button-sidebar
- components: [LinearPanel]
  name: 'gauge-background '
- components: [LinearPanel, ColumnPanel]
  name: score-tile-background
- components: [Label]
  name: contact-details-saved-values
- components: [Button]
  name: contact-button
- components: [ColumnPanel]
  name: left-discover-page
- components: [Button]
  name: play-spotify-button
- components: [ColumnPanel]
  name: spotify-footer-class
- components: [Button]
  name: play-spotify-button-artist
- components: [Button]
  name: autoplay-toggle-button
- components: [ColumnPanel]
  name: tile-background-general
- components: [Label, RichText]
  name: header-2
- components: [Label, RichText]
  name: header-3
- components: [Label, RichText, Button]
  name: header-4
- components: [Label, Button]
  name: transition-effect
- components: [ColumnPanel]
  name: tile-background-left
- components: [ColumnPanel]
  name: tile-background-right
- components: [Label, RichText, Button, TextBox]
  name: header-8
- components: [Label, RichText, Button, Link]
  name: header-10
- components: [Button]
  name: call-to-action-button
- components: [Label, RichText, Button, Link, TextBox]
  name: header-5
- components: [LinearPanel]
  name: position-bottom
- components: [LinearPanel, ColumnPanel]
  name: highlights-tile-background
- components: [Label, RichText, Button, Link]
  name: header-5_bold
- components: [Label, RichText, Button]
  name: header-6_grey
- components: [ColumnPanel, GridPanel]
  name: equal-height-container
- components: [ColumnPanel]
  name: highlights-tile-background-for-col
- components: [Label, RichText, Button, Link]
  name: header-7
- components: [Label, RichText, Button, Link]
  name: header-6_bold
- components: [ColumnPanel]
  name: tile-background-general-no-background
- components: [LinearPanel, ColumnPanel]
  name: score-tile-background-larger
- components: [Image]
  name: navbar-image
- components: [XYPanel]
  name: talent-dev-custom-class
- components: [ColumnPanel, GridPanel]
  name: home-page
- components: [XYPanel]
  name: full-page-length
- components: [TextBox]
  name: search-bar-related-artists
- components: [FlowPanel]
  name: rampup-steps
- components: [Label, Button, Link]
  name: rampup-labels
- components: [TextBox]
  name: rampup-text-field
- components: [Button]
  name: opacity-100
- components: [Button]
  name: opacity-50
- components: [Button]
  name: opacity-25
- components: [Button]
  name: back-button
- components: [Slider]
  name: slider
- components: [ColumnPanel]
  name: level-of-pop-page
- components: [Label, RichtText, Button, TextBox, Link]
  name: header-6
- components: [TextBox, Button]
  name: slider-refresh
- components: [TextBox, Button]
  name: slider-inputbox
- components: [Image]
  name: artist-image
- components: [Link]
  name: genre-box-deselect
- components: [Link]
  name: genre-box-deactive
- components: [Link]
  name: genre-box
- components: [ColumnPanel, FlowPanel]
  name: margin
- components: [Button, FlowPanel]
  name: top-margin-button
- components: [Link, Label]
  name: header-7-on-white-bg
- components: [Link]
  name: margin-padding-0
- components: [Link, Label]
  name: header-3-on-white-bg
- components: [Button]
  name: 'slider-refresh-growth '
- components: [Notification]
  name: alert-notification
- components: [FlowPanel, ColumnPanel]
  name: section-background-flex
- components: [Link]
  name: section_buttons-flex-items
- components: [RichText]
  name: no-padding
- components: [ColumnPanel]
  name: section-background-justify
