roles:
- name: title
  components: [Label]
  display_in_toolbox: false
- name: card
  components: [ColumnPanel]
  display_in_toolbox: false
  title: Card
- name: description
  components: [Label, Link]
- name: artist_name
  components: [Label, Link]
- name: grid
  components: [GridPanel, ColumnPanel, Link, Image]
- name: feature
  components: [Label, Button]
- name: value
  components: [Label]
- name: eval_button
  components: [Button]
- name: sub_title
  components: [Label]
- name: table_content
  components: [RepeatingPanel, Link]
- name: text_box
  components: [TextBox]
- name: call_to_action_button
  components: [Button]
- name: landingpage_noartists_background
  components: [ColumnPanel]
- name: landingpage_artist_background
  components: [ColumnPanel]
- name: landingpage_artist2_background
  components: [ColumnPanel]
- name: input_margin
  components: [ColumnPanel]
- name: table_content_small
  components: [RepeatingPanel]
- name: table_header
  components: [DataGrid]
- name: investigate_value
  components: [Label, Link]
- name: investigate_feature
  components: [Label, Link]
- name: text_box_small
  components: [TextBox, DropDown, TextArea, DatePicker]
- name: artist_name_shadow
  components: [Label, Link]
- name: note
  components: [Label]
color_scheme:
  preset_groups:
  - name: Accent
    options:
    - name: Blue
      colors:
      - {name: Accent 1, color: '#2196F3'}
      - {name: Accent 2, color: '#1976D2'}
    - name: Orange
      colors:
      - {name: Accent 1, color: '#FF9800'}
      - {name: Accent 2, color: '#F57C00'}
    - name: Red
      colors:
      - {name: Accent 1, color: '#F44336'}
      - {name: Accent 2, color: '#D32F2F'}
    - name: Pink
      colors:
      - {name: Accent 1, color: '#E91E63'}
      - {name: Accent 2, color: '#C2185B'}
    - name: Purple
      colors:
      - {name: Accent 1, color: '#9C27B0'}
      - {name: Accent 2, color: '#7B1FA2'}
    - name: Deep Purple
      colors:
      - {name: Accent 1, color: '#673AB7'}
      - {name: Accent 2, color: '#512DA8'}
    - name: Indigo
      colors:
      - {name: Accent 1, color: '#3F51B5'}
      - {name: Accent 2, color: '#303F9F'}
    - name: Light Blue
      colors:
      - {name: Accent 1, color: '#03A9F4'}
      - {name: Accent 2, color: '#0288D1'}
    - name: Cyan
      colors:
      - {name: Accent 1, color: '#00BCD4'}
      - {name: Accent 2, color: '#0097A7'}
    - name: Teal
      colors:
      - {name: Accent 1, color: '#009688'}
      - {name: Accent 2, color: '#00796B'}
    - name: Green
      colors:
      - {name: Accent 1, color: '#4CAF50'}
      - {name: Accent 2, color: '#388E3C'}
    - name: Light Green
      colors:
      - {name: Accent 1, color: '#8BC34A'}
      - {name: Accent 2, color: '#689F38'}
    - name: Lime
      colors:
      - {name: Accent 1, color: '#CDDC39'}
      - {name: Accent 2, color: '#AFB42B'}
    - name: Deep orange
      colors:
      - {name: Accent 1, color: '#FF5722'}
      - {name: Accent 2, color: '#E64A19'}
    - name: Brown
      colors:
      - {name: Accent 1, color: '#795548'}
      - {name: Accent 2, color: '#5D4037'}
    - name: Grey
      colors:
      - {name: Accent 1, color: '#9E9E9E'}
      - {name: Accent 2, color: '#616161'}
  colors:
  - {name: Accent 1, color: '#9E9E9E'}
  - {name: Accent 2, color: '#616161'}
  - {name: Background, color: '#D7D7D7'}
  - {name: Header Background, color: '#333333'}
  - {name: Sidebar Background, color: 'rgb(51, 51, 51)'}
  - {name: Main_Black, color: 'rgb(25, 28, 26)'}
  - {name: Grid_Black, color: 'rgb(40, 40, 40)'}
  - {name: Orange, color: 'rgb(253, 101, 45)'}
  - {name: Text_White, color: 'rgb(255, 255, 255)'}
  - {name: Text_DecentWhite, color: 'rgb(235, 235, 235)'}
  - {name: Text_Grey, color: 'rgb(200, 200, 200)'}
  - {name: Text_DarkGrey, color: 'rgb(175, 175, 175)'}
  - {name: Text_LightBlack, color: 'rgb(40, 40, 40)'}
